FROM maven:3.8.4-openjdk-17-slim AS build

COPY /spring-server/pom.xml /app/
COPY /spring-server/src /app/src/

WORKDIR /app

RUN mvn clean install

FROM azul/zulu-openjdk:17-jre

COPY --from=build /app/target/FippPay-0.0.1-SNAPSHOT.jar /app/app.jar

WORKDIR /app
EXPOSE 8080

CMD ["java", "-jar", "app.jar"]